### Send GET request to get all posts
GET localhost:8080/api/posts
Content-Type: application/json

### Send POST request with json body to create post
POST localhost:8080/api/posts
Content-Type: application/json

{
  "title": "Olá Mundo",
  "content": "Esse é um teste inicial",
  "author": "Kate"
}

### Send GET request to get post by id
GET localhost:8080/api/posts/1
Content-Type: application/json

### Send GET request to search post by term
GET localhost:8080/api/posts/search?term=Olá adeus
Content-Type: application/json

### Send PUT request to update a post with json body by id
PUT localhost:8080/api/posts/1
Content-Type: application/json

{
  "title": "Adeus Mundo",
  "content": "Esse é um teste final"
}

### Send DELETE request to delete a post by id
DELETE localhost:8080/api/posts/1
Content-Type: application/json
