version: '3.8'

services:
  # PostgreSQL service
  postgresdb:
    container_name: profzera_db
    image: postgres:14.18
    ports:
      # Maps container port 5432 to host port 5432
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=profzera_db
    volumes:
      # Data persistence volume
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Backend Node.js
  backend:
    container_name: profzera_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/profzera-app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=postgresdb
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=profzera_db
    depends_on:
      - postgresdb
    restart: unless-stopped

    # Frontend React
    frontend:
      container_name: profzera_frontend
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "5173:5173"
      volumes:
        - ./frontend:/app
        - /app/node_modules
      restart: unless-stopped

volumes:
  postgres_data:
