version: '3.8'

services:
  # PostgreSQL service
  postgresdb:
    container_name: profzera_db
    image: postgres:17.4
    hostname: ${DB_HOST}
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Backend Node.js
  backend:
    container_name: profzera_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/profzera-app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - postgresdb
    restart: unless-stopped

volumes:
  postgres_data:
