version: '3.8'

services:
  # PostgreSQL service
  postgresdb:
    container_name: profzera_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Senha123
      - POSTGRES_DB=profzera_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Backend Node.js
  backend:
    container_name: profzera_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/profzera-app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=Senha123
      - DB_NAME=profzera_db
    depends_on:
      - postgresdb
    restart: unless-stopped

volumes:
  postgres_data:
