openapi: 3.0.0
info:
  title: Profzera Posts API
  version: 1.0.0
  description: |
    API completa para gestão de posts acadêmicos.
    - Rotas públicas: Listagem e leitura de posts
    - Rotas protegidas: Criação/edição (somente para professores, requer autenticação)
servers:
  - url: http://localhost:8080
    description: Ambiente local
  - url: https://api.profzera.com/v1
    description: Produção

paths:
  $ref: './paths/posts.yaml'
  $ref: './paths/posts_{id}.yaml'
  $ref: './paths/posts_search.yaml'
  $ref: './paths/posts_admin.yaml'

components:
  schemas:
    $ref: './schemas/post.yaml'
    $ref: './schemas/error.yaml'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    postId:
      name: id
      in: path
      description: ID do post
      required: true
      schema:
        type: integer
        example: 1
    searchQuery:
      name: q
      in: query
      description: Termo de busca
      required: true
      schema:
        type: string
        example: "nodejs"