name: CD Pipeline

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.katehori }}
        password: ${{ secrets.dckr_pat_EMUajoziPh5t4jqJZOShf5Y2c5s }}

    - name: Build and push Docker image
      run: |
        docker build -t katehori/profzera-app":${{ github.sha }} .
        docker push katehori/profzera-app":${{ github.sha }}
