name: CI Pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run tests with coverage
      uses: ArtiomTr/jest-coverage-report-action@v2.1.2
      id: coverage
      with:
        annotations: none
        package-manager: npm
        test-script: npm test:coverage
        icons: emoji