name: CI Pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          DB_USER: admin
          DB_PASSWORD: Senha@123
          DB_NAME: profzera_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm intall

    - name: Run tests
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USER: admin
        DB_PASSWORD: Senha@123
        DB_NAME: profzera_db
        NODE_ENV: test
      run: npm test

    - name: Build Docker image
      run: docker build -t profzera-app .